[package]
name    = "icelines-site"
version.workspace = true
edition.workspace = true

[dependencies]
icelines-core  = { path = "../icelines-core" }
icelines-fetch = { path = "../icelines-fetch" }
thiserror.workspace = true
serde.workspace     = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
regex.workspace    = true
