[package]
name = "icelines-query"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
icelines-core = { path = "../icelines-core" }
thiserror.workspace = true
chrono.workspace = true

[dev-dependencies]
proptest.workspace = true
serde_json.workspace = true
slice-core.workspace = true
