param(
    [Parameter(Mandatory = $true)]
    [string]$Pulse,

    [switch]$Sync
)

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$wavesRoot = Join-Path $root "design\waves"
$indexPath = Join-Path $wavesRoot "PHASES.md"

if (!(Test-Path $indexPath)) {
    throw "Missing wave index: $indexPath"
}

$activeLine = Get-Content $indexPath | Where-Object { $_ -match "\|\s*\[([^\]]+)\]\(([^)]+)\)\s*\|\s*active\s*\|" } | Select-Object -First 1
if (!$activeLine) {
    throw "No active wave found in $indexPath"
}

$activeRel = [regex]::Match($activeLine, "\]\(([^)]+)\)").Groups[1].Value
$waveDir = Join-Path $wavesRoot (Split-Path -Parent $activeRel)
$waveName = [regex]::Match($activeLine, "\|\s*\[([^\]]+)\]").Groups[1].Value

$pulseNumber = "{0:d2}" -f [int]$Pulse
$planPath = Join-Path $waveDir "plans\pulse-$pulseNumber.md"
$forkPath = Join-Path $waveDir "forks\pulse-$pulseNumber.md"

if (!(Test-Path $planPath)) {
    throw "Missing pulse plan: $planPath"
}

if ($Sync) {
    throw "Sync is intentionally manual for now: copy checked gates from $forkPath back to $planPath after review."
}

$plan = Get-Content $planPath -Raw
$titleMatch = [regex]::Match($plan, "(?m)^#\s+(.+)$")
$title = if ($titleMatch.Success) { $titleMatch.Groups[1].Value } else { "Pulse $pulseNumber" }
$title = [regex]::Replace($title, "^Pulse\s+$pulseNumber\s*-\s*", "")

$roles = @()
$inRoles = $false
foreach ($line in ($plan -split "`r?`n")) {
    if ($line -match "^governing_roles:\s*$") {
        $inRoles = $true
        continue
    }
    if ($inRoles -and $line -match "^\s*-\s+([A-Za-z0-9_-]+)\s*$") {
        $roles += $Matches[1]
        continue
    }
    if ($inRoles -and $line -match "^[A-Za-z0-9_-]+:") {
        break
    }
}

$roleBlocks = New-Object System.Collections.Generic.List[string]
foreach ($role in $roles) {
    $rolePath = Join-Path $root ".roles\$role.md"
    if (!(Test-Path $rolePath)) {
        throw "Missing role '$role' at $rolePath"
    }
    $roleText = Get-Content $rolePath -Raw
    $roleBlocks.Add("### $role`n`n$roleText")
}

$content = @"
# Fork Context: Pulse $pulseNumber - $title
# Wave: $waveName

> Generated by scripts/wave-fork.ps1. Read this file completely before acting.
> Do not work from chat memory. Check off gates here as you complete them.

---

## Pulse Plan

$plan

---

## Governing Roles

$($roleBlocks -join "`n---`n`n")

---

## Execution Contract

You are working in `$root`.

1. Read this fork file completely.
2. Apply every governing role above.
3. Keep changes inside the pulse ownership scope.
4. Run every gate listed in the pulse.
5. Check off completed gates in this fork file.
6. Report files changed, tests run, and any unchecked gates.

Stop if the pulse needs a new ViewModel contract, network data without a
fixture, a GET-backed mutation, or unrelated phase work.
"@

New-Item -ItemType Directory -Force (Split-Path -Parent $forkPath) | Out-Null
Set-Content -Path $forkPath -Value $content -Encoding UTF8
Write-Output "Fork created: $forkPath"
