use ratatui::text::Line;

/// Render the help overlay content.
pub fn help_lines() -> Vec<Line<'static>> {
    vec![
        Line::from("  IceLines TUI — Key Bindings"),
        Line::from("  ─────────────────────────────"),
        Line::from("  q / Ctrl+C   Quit"),
        Line::from("  ?            Help (this screen)"),
        Line::from("  /            Search (players or schedule team / matchup)"),
        Line::from("  Tab          Cycle main screens"),
        Line::from("  1–6          Jump directly to a tab"),
        Line::from("  ↑/↓  j/k     Move cursor"),
        Line::from("  ←/→          Sub-view  ·  on Schedule: previous / next week"),
        Line::from("  Enter        Select / drill down"),
        Line::from("  Esc          Go back / clear search"),
        Line::from("  r            Refresh / retry current view"),
        Line::from("  d            Toggle league depth chart  (s: scoring on Depth)"),
        Line::from("  t            On Schedule: jump to today's week"),
        Line::from("  y            Season picker (time-travel)"),
        Line::from("  F            Admin overlay"),
        Line::from(""),
        Line::from("  Tabs: League · Stats · Scores · Schedule · Groups · Playoffs"),
        Line::from("  Enter on team → Team lineup card"),
        Line::from("  Enter on player → Player profile"),
        Line::from("  /SEA → team filter   ·   /NYR WSH → matchup filter"),
    ]
}

/// Phase Adams.5 — comprehensive command reference for the MDI
/// dashboard's chat-CLI command bar. Shown via `?` or `/help`
/// when `app.mdi.is_some()`.
pub fn mdi_help_lines() -> Vec<Line<'static>> {
    vec![
        Line::from("  IceLines MDI Dashboard — Command Bar Reference"),
        Line::from("  ───────────────────────────────────────────────"),
        Line::from(""),
        Line::from("  TO ENTER A COMMAND"),
        Line::from("    :              focus bar with empty input"),
        Line::from("    /              focus bar with `/` already typed (slash cmds)"),
        Line::from("    Esc            cancel + clear input"),
        Line::from("    Backspace      delete; releases focus when input is empty"),
        Line::from("    Enter          submit"),
        Line::from(""),
        Line::from("  WORKSPACE SWAPS (no args)"),
        Line::from("    stats          → Stats (Queries) screen"),
        Line::from("    goalies        → Goalies leaderboard"),
        Line::from("    transactions   → Transactions feed   (alias: txs)"),
        Line::from("    playoffs       → Playoffs bracket"),
        Line::from("    depth          → Depth chart"),
        Line::from("    scores         → Today's scores"),
        Line::from("    schedule       → Weekly schedule"),
        Line::from("    favorites      → Favorites screen"),
        Line::from(""),
        Line::from("  WORKSPACE SWAPS (with args)"),
        Line::from("    player <name>           → player card           e.g. player Bedard"),
        Line::from("    team <ABBR>             → team depth chart      e.g. team EDM"),
        Line::from("    team <ABBR> season      → team's full schedule"),
        Line::from("    compare <a>             → similar peers"),
        Line::from("    compare <a> <b>         → head-to-head"),
        Line::from("    box <game-id>           → boxscore detail"),
        Line::from(""),
        Line::from("  FREE-FORM QUERY (Phase Art Ross filters)"),
        Line::from("    query <filter>          → Stats screen with filter applied"),
        Line::from("                              e.g. query g >= 30 AND age <= 25"),
        Line::from(""),
        Line::from("  WRITE ACTIONS"),
        Line::from("    /fav add <name>         add to Favorites"),
        Line::from("    /fav remove <name>      remove from Favorites"),
        Line::from(""),
        Line::from("  LAYOUT (slash-only)"),
        Line::from("    /hide favorites         hide Favorites pane (also Ctrl+H)"),
        Line::from("    /hide schedule          hide Schedule pane  (also Ctrl+L)"),
        Line::from("    /show favorites         restore Favorites pane"),
        Line::from("    /show schedule          restore Schedule pane"),
        Line::from(""),
        Line::from("  META"),
        Line::from("    /help          this screen          (alias: /h, /?)"),
        Line::from("    /quit          exit                  (also bare q)"),
        Line::from(""),
        Line::from("  GLOBAL HOTKEYS (work without entering the bar)"),
        Line::from("    q              quit"),
        Line::from("    Ctrl+H         toggle Favorites pane"),
        Line::from("    Ctrl+L         toggle Schedule pane"),
        Line::from("    ?              this help screen"),
    ]
}
