[package]
name = "icelines-wasm"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
icelines-core = { path = "../icelines-core" }
icelines-data = { path = "../icelines-data" }
icelines-query = { path = "../icelines-query" }
icelines-sources = { path = "../icelines-sources" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
chrono.workspace = true
sha2.workspace = true
wasm-bindgen = "=0.2.118"
