[package]
name    = "icelines-core"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace        = true
serde.workspace            = true
serde_json.workspace       = true
regex.workspace            = true
sha2.workspace             = true
once_cell.workspace        = true
static_assertions.workspace = true

[dev-dependencies]
proptest = { workspace = true }
