[package]
name    = "icelines-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "icelines"
path = "src/main.rs"

[dependencies]
icelines-core  = { path = "../icelines-core" }
icelines-fetch = { path = "../icelines-fetch" }
icelines-site  = { path = "../icelines-site" }
clap.workspace        = true
anyhow.workspace      = true
tokio.workspace       = true
comfy-table.workspace = true
owo-colors.workspace  = true
serde_json.workspace  = true
toml.workspace        = true
